# Dependabot configuration for automatic dependency updates
# This file configures GitHub's Dependabot to automatically check for
# and create pull requests for dependency updates

version: 2
updates:
  # Rust/Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername" # Replace with actual GitHub username
    assignees:
      - "yourusername" # Replace with actual GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      # Ignore patch updates for stable dependencies
      - dependency-name: "serde"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "tokio"
        update-types: ["version-update:semver-patch"]
    groups:
      # Group related dependencies together
      serde-ecosystem:
        patterns:
          - "serde*"
        update-types:
          - "minor"
          - "patch"
      tokio-ecosystem:
        patterns:
          - "tokio*"
        update-types:
          - "minor"
          - "patch"
      testing-deps:
        patterns:
          - "tempfile"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    reviewers:
      - "yourusername" # Replace with actual GitHub username
    assignees:
      - "yourusername" # Replace with actual GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-ecosystem:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 3
    reviewers:
      - "yourusername" # Replace with actual GitHub username
    assignees:
      - "yourusername" # Replace with actual GitHub username
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
